@echo off
setlocal
set "SELF=%~f0"
set "LOCAL_JRE=%LOCALAPPDATA%\yt-audio-downloader\jre"
set "JAVA_EXE=%LOCAL_JRE%\bin\javaw.exe"

REM javaw (em vez de java) roda sem abrir uma janela de console, e "start" solta
REM o processo para que este .bat encerre e feche a janela imediatamente.
where javaw >nul 2>nul
if %ERRORLEVEL%==0 (
    start "" javaw -jar "%SELF%"
    goto :eof
)

if exist "%JAVA_EXE%" (
    start "" "%JAVA_EXE%" -jar "%SELF%"
    goto :eof
)

echo Java nao encontrado. Baixando um Java portatil ^(Eclipse Temurin 21, ~45MB, uma unica vez^)...
powershell -NoProfile -ExecutionPolicy Bypass -EncodedCommand "JABFAHIAcgBvAHIAQQBjAHQAaQBvAG4AUAByAGUAZgBlAHIAZQBuAGMAZQAgAD0AIAAnAFMAdABvAHAAJwAKACQAbABvAGMAYQBsAEoAcgBlACAAPQAgAEoAbwBpAG4ALQBQAGEAdABoACAAJABlAG4AdgA6AEwATwBDAEEATABBAFAAUABEAEEAVABBACAAJwB5AHQALQBhAHUAZABpAG8ALQBkAG8AdwBuAGwAbwBhAGQAZQByAFwAagByAGUAJwAKACQAegBpAHAAIAA9ACAASgBvAGkAbgAtAFAAYQB0AGgAIAAkAGUAbgB2ADoAVABFAE0AUAAgACcAeQB0AGEAdQBkAGkAbwAtAGoAcgBlAC4AegBpAHAAJwAKACQAdQByAGwAIAA9ACAAJwBoAHQAdABwAHMAOgAvAC8AYQBwAGkALgBhAGQAbwBwAHQAaQB1AG0ALgBuAGUAdAAvAHYAMwAvAGIAaQBuAGEAcgB5AC8AbABhAHQAZQBzAHQALwAyADEALwBnAGEALwB3AGkAbgBkAG8AdwBzAC8AeAA2ADQALwBqAHIAZQAvAGgAbwB0AHMAcABvAHQALwBuAG8AcgBtAGEAbAAvAGUAYwBsAGkAcABzAGUAPwBwAHIAbwBqAGUAYwB0AD0AagBkAGsAJwAKAEkAbgB2AG8AawBlAC0AVwBlAGIAUgBlAHEAdQBlAHMAdAAgAC0AVQByAGkAIAAkAHUAcgBsACAALQBPAHUAdABGAGkAbABlACAAJAB6AGkAcAAgAC0AVQBzAGUAQgBhAHMAaQBjAFAAYQByAHMAaQBuAGcACgBOAGUAdwAtAEkAdABlAG0AIAAtAEkAdABlAG0AVAB5AHAAZQAgAEQAaQByAGUAYwB0AG8AcgB5ACAALQBGAG8AcgBjAGUAIAAtAFAAYQB0AGgAIAAkAGwAbwBjAGEAbABKAHIAZQAgAHwAIABPAHUAdAAtAE4AdQBsAGwACgBFAHgAcABhAG4AZAAtAEEAcgBjAGgAaQB2AGUAIAAtAFAAYQB0AGgAIAAkAHoAaQBwACAALQBEAGUAcwB0AGkAbgBhAHQAaQBvAG4AUABhAHQAaAAgACQAbABvAGMAYQBsAEoAcgBlACAALQBGAG8AcgBjAGUACgAkAGkAbgBuAGUAcgAgAD0AIABHAGUAdAAtAEMAaABpAGwAZABJAHQAZQBtACAALQBQAGEAdABoACAAJABsAG8AYwBhAGwASgByAGUAIAB8ACAAVwBoAGUAcgBlAC0ATwBiAGoAZQBjAHQAIAB7ACAAJABfAC4AUABTAEkAcwBDAG8AbgB0AGEAaQBuAGUAcgAgAH0AIAB8ACAAUwBlAGwAZQBjAHQALQBPAGIAagBlAGMAdAAgAC0ARgBpAHIAcwB0ACAAMQAKAGkAZgAgACgAJABpAG4AbgBlAHIAKQAgAHsACgAgACAAIAAgAEcAZQB0AC0AQwBoAGkAbABkAEkAdABlAG0AIAAtAFAAYQB0AGgAIAAkAGkAbgBuAGUAcgAuAEYAdQBsAGwATgBhAG0AZQAgAHwAIABNAG8AdgBlAC0ASQB0AGUAbQAgAC0ARABlAHMAdABpAG4AYQB0AGkAbwBuACAAJABsAG8AYwBhAGwASgByAGUAIAAtAEYAbwByAGMAZQAKACAAIAAgACAAUgBlAG0AbwB2AGUALQBJAHQAZQBtACAALQBQAGEAdABoACAAJABpAG4AbgBlAHIALgBGAHUAbABsAE4AYQBtAGUAIAAtAFIAZQBjAHUAcgBzAGUAIAAtAEYAbwByAGMAZQAKAH0ACgBSAGUAbQBvAHYAZQAtAEkAdABlAG0AIAAtAFAAYQB0AGgAIAAkAHoAaQBwACAALQBGAG8AcgBjAGUACgA="

if not exist "%JAVA_EXE%" (
    echo.
    echo Falha ao preparar o Java automaticamente. Instale manualmente em: https://adoptium.net
    pause
    exit /b 1
)

start "" "%JAVA_EXE%" -jar "%SELF%"
goto :eof
